// Generated by CoffeeScript 2.4.1
(function() {
  'use strict';
  var CND, PD, XXX_SETTINGS, alert, assign, badge, debug, echo, help, info, log, rpr, urge, warn, whisper;

  //###########################################################################################################
  CND = require('cnd');

  rpr = CND.rpr;

  badge = '明快打字机/TRANSCRIPTORS/edict2かな漢字変換';

  log = CND.get_logger('plain', badge);

  debug = CND.get_logger('debug', badge);

  info = CND.get_logger('info', badge);

  warn = CND.get_logger('warn', badge);

  alert = CND.get_logger('alert', badge);

  help = CND.get_logger('help', badge);

  urge = CND.get_logger('urge', badge);

  whisper = CND.get_logger('whisper', badge);

  echo = CND.echo.bind(CND);

  //...........................................................................................................
  PD = require('pipedreams');

  assign = Object.assign;

  //...........................................................................................................
  XXX_SETTINGS = {
    max_search_results: 500,
    search_with_lower_case: true
  };

  //-----------------------------------------------------------------------------------------------------------
  this.display_name = 'edict2かな漢字変換';

  this.sigil = 'か漢';

  //-----------------------------------------------------------------------------------------------------------
  this.kanji_from_pinyin = function(text) {
    var R, i, j, lemma, lemmata, len, len1, pinyin, results;
    if (XXX_SETTINGS.search_with_lower_case) {
      text = text.toLowerCase();
    }
    results = kanji_triode.find(text);
    R = [];
    for (i = 0, len = results.length; i < len; i++) {
      [pinyin, lemmata] = results[i];
      for (j = 0, len1 = lemmata.length; j < len1; j++) {
        lemma = lemmata[j];
        R.push(lemma);
      }
      if (R.length > XXX_SETTINGS.max_search_results) {
        R.length = XXX_SETTINGS.max_search_results;
        break;
      }
    }
    return R;
  };

  //-----------------------------------------------------------------------------------------------------------
  this.on_transcribe = function(d) {
    var ntext, otext;
    ({otext} = d.value);
    if (!(otext.length > 0)) {
      return null;
    }
    ntext = `[${otext}]`;
    OPS.log(PD.new_event('^replace-text', assign({}, d.value, {ntext})));
    XE.emit(PD.new_event('^replace-text', assign({}, d.value, {ntext})));
    return null;
  };

}).call(this);

//# sourceMappingURL=edict2u-kanji.ts.js.map
