// Generated by CoffeeScript 2.4.1
(function() {
  'use strict';
  var CND, PD, XXX_SETTINGS, alert, assign, badge, debug, echo, help, info, kanji_triode, log, rpr, urge, warn, whisper;

  //###########################################################################################################
  CND = require('cnd');

  rpr = CND.rpr;

  badge = '明快打字机/TRANSCRIPTORS/SIMPLE-HANZI';

  log = CND.get_logger('plain', badge);

  debug = CND.get_logger('debug', badge);

  info = CND.get_logger('info', badge);

  warn = CND.get_logger('warn', badge);

  alert = CND.get_logger('alert', badge);

  help = CND.get_logger('help', badge);

  urge = CND.get_logger('urge', badge);

  whisper = CND.get_logger('whisper', badge);

  echo = CND.echo.bind(CND);

  //...........................................................................................................
  PD = require('pipedreams');

  assign = Object.assign;

  //...........................................................................................................
  XXX_SETTINGS = {
    max_search_results: 500,
    search_with_lower_case: true
  };

  //-----------------------------------------------------------------------------------------------------------
  this.display_name = '簡單繁體漢字';

  this.sigil = '繁';

  kanji_triode = null;

  //...........................................................................................................
  this.initialized = false;

  //-----------------------------------------------------------------------------------------------------------
  this.initialize = function() {
    this.initialized = true;
    return kanji_triode = require('../../.cache/cedict_ts.cdt.js');
  };

  //-----------------------------------------------------------------------------------------------------------
  this.kanji_from_pinyin = function(text) {
    var R, i, j, lemma, lemmata, len, len1, pinyin, results;
    if (XXX_SETTINGS.search_with_lower_case) {
      text = text.toLowerCase();
    }
    results = kanji_triode.find(text);
    R = [];
    for (i = 0, len = results.length; i < len; i++) {
      [pinyin, lemmata] = results[i];
      for (j = 0, len1 = lemmata.length; j < len1; j++) {
        lemma = lemmata[j];
        R.push(lemma);
      }
      if (R.length > XXX_SETTINGS.max_search_results) {
        R.length = XXX_SETTINGS.max_search_results;
        break;
      }
    }
    return R;
  };

  //-----------------------------------------------------------------------------------------------------------
  this.on_transcribe = function(d) {
    var candidates, otext;
    if (!this.initialized) {
      this.initialize();
    }
    ({otext} = d.value);
    if (otext.length === 0) {
      return XE.emit(PD.new_event('^candidates', {
        candidates: []
      }));
    }
    candidates = this.kanji_from_pinyin(otext);
    XE.emit(PD.new_event('^candidates', assign({candidates}, d.value)));
    return null;
  };

}).call(this);

//# sourceMappingURL=simple-hanzi.ts.js.map
