// Generated by CoffeeScript 2.3.2
(function() {
  'use strict';
  var CND, PD, _transcribe, alert, assign, badge, debug, echo, help, info, inspect, log, rpr, urge, warn, whisper, xrpr;

  //###########################################################################################################
  CND = require('cnd');

  rpr = CND.rpr;

  badge = '明快打字机/TRANSCRIPTORS/SIMPLE-HIRAGANA';

  log = CND.get_logger('plain', badge);

  debug = CND.get_logger('debug', badge);

  info = CND.get_logger('info', badge);

  warn = CND.get_logger('warn', badge);

  alert = CND.get_logger('alert', badge);

  help = CND.get_logger('help', badge);

  urge = CND.get_logger('urge', badge);

  whisper = CND.get_logger('whisper', badge);

  echo = CND.echo.bind(CND);

  //...........................................................................................................
  assign = Object.assign;

  ({inspect} = require('util'));

  xrpr = function(x) {
    return inspect(x, {
      colors: true,
      breakLength: 2e308,
      maxArrayLength: 2e308,
      depth: 2e308
    });
  };

  PD = require('pipedreams');

  //-----------------------------------------------------------------------------------------------------------
  this.load_keyboard = function() {
    /* TAINT compare filedates, refresh cache */
    return require('../../.cache/jp_kana.hrgn.keyboard.wsv.js');
  };

  // return require '../../.cache/gr_gr.keyboard.wsv.js'
  _transcribe = this.load_keyboard();

  //-----------------------------------------------------------------------------------------------------------
  this.transcribe = function(text) {
    var R, chr, i, len, ref;
    R = '';
    ref = Array.from(text);
    for (i = 0, len = ref.length; i < len; i++) {
      chr = ref[i];
      R = _transcribe(R + chr);
    }
    return R;
  };

  //-----------------------------------------------------------------------------------------------------------
  this.display_name = '簡単なひらがな';

  //-----------------------------------------------------------------------------------------------------------
  this.init = function() {
    return OPS.log(`${badge}/init()`);
  };

  //-----------------------------------------------------------------------------------------------------------
  this.on_transcribe = function(d) {
    var ntext, otext;
    //.........................................................................................................
    // whisper 'µ34343', xrpr change
    ({otext} = d.value);
    ntext = this.transcribe(otext);
    if (otext !== ntext) {
      OPS.log('µ34343', (rpr(otext)) + ' -> ' + (rpr(ntext)));
      XE.emit(PD.new_event('^replace-text', assign({}, d.value, {ntext})));
    }
    return null;
  };

}).call(this);

//# sourceMappingURL=simple-hiragana.ts.js.map
