// Generated by CoffeeScript 2.4.1
(function() {
  'use strict';
  var CND, PATH, alert, badge, debug, echo, help, info, log, new_numeral, rpr, urge, warn, whisper;

  //###########################################################################################################
  CND = require('cnd');

  rpr = CND.rpr;

  badge = '明快打字机/HELPERS';

  log = CND.get_logger('plain', badge);

  debug = CND.get_logger('debug', badge);

  info = CND.get_logger('info', badge);

  warn = CND.get_logger('warn', badge);

  alert = CND.get_logger('alert', badge);

  help = CND.get_logger('help', badge);

  urge = CND.get_logger('urge', badge);

  whisper = CND.get_logger('whisper', badge);

  echo = CND.echo.bind(CND);

  //...........................................................................................................
  PATH = require('path');

  new_numeral = require('numeral');

  //...........................................................................................................
  this.assign = Object.assign;

  this.abspath = function(...P) {
    return PATH.resolve(PATH.join(__dirname, '..', ...P));
  };

  this.relpath = function(...P) {
    return PATH.relative(process.cwd(), PATH.join(...P));
  };

  this.format_float = function(x) {
    return (new_numeral(x)).format('0,0.000');
  };

  this.format_integer = function(x) {
    return (new_numeral(x)).format('0,0');
  };

}).call(this);

//# sourceMappingURL=helpers.js.map
