// Generated by CoffeeScript 2.3.2
(function() {
  'use strict';
  var CND, DB, PATH, PD, TRIODE, XE, alert, badge, buffer, debug, echo, help, info, jr, kana_keyboard, kana_triode, log, rpr, urge, warn, whisper;

  //###########################################################################################################
  CND = require('cnd');

  rpr = CND.rpr;

  badge = '明快打字机/KANA-INPUT';

  log = CND.get_logger('plain', badge);

  debug = CND.get_logger('debug', badge);

  info = CND.get_logger('info', badge);

  warn = CND.get_logger('warn', badge);

  alert = CND.get_logger('alert', badge);

  help = CND.get_logger('help', badge);

  urge = CND.get_logger('urge', badge);

  whisper = CND.get_logger('whisper', badge);

  echo = CND.echo.bind(CND);

  //...........................................................................................................
  PATH = require('path');

  //...........................................................................................................
  // parallel                  = require './parallel-promise'
  DB = require('./db');

  //...........................................................................................................
  // _format                   = require 'pg-format'
  // I                         = ( value ) -> _format '%I', value
  // L                         = ( value ) -> _format '%L', value
  //...........................................................................................................
  ({jr} = CND);

  PD = require('pipedreams');

  // { remote, }               = require 'electron'
  // XE                        = remote.require './xemitter'
  XE = require('./xemitter');

  //...........................................................................................................
  TRIODE = require('triode');

  kana_keyboard = require('../db/kana.keyboard.json');

  kana_triode = null;

  buffer = [];

  //-----------------------------------------------------------------------------------------------------------
  this.load_kana_triode = function() {
    var i, len, source, target;
    kana_triode = TRIODE.new();
    for (i = 0, len = kana_keyboard.length; i < len; i++) {
      [source, target] = kana_keyboard[i];
      kana_triode[source] = target;
    }
    return null;
  };

  // #-----------------------------------------------------------------------------------------------------------
  // XE.listen_to_all ( key, d ) -> whisper 'µ44532', jr d
  urge(__filename);

  //-----------------------------------------------------------------------------------------------------------
  XE.contract('^input', function(d) {
    var matches;
    urge('µ55401', jr(d));
    matches = kana_triode[d.value];
    if (matches.length !== 1) {
      return null;
    }
    return matches[0][1];
  });

  (async function() {
    return debug('µ98933', (await XE.emit(PD.new_event('^input', 'kyo'))));
  })();

  //-----------------------------------------------------------------------------------------------------------
  XE.listen_to('<keyboard-level', function(d) {});

  // urge 'µ55402', jr d

  //-----------------------------------------------------------------------------------------------------------
  XE.listen_to('>keyboard-level', function(d) {});

  // urge 'µ55403', jr d

  //###########################################################################################################
  this.load_kana_triode();

}).call(this);

//# sourceMappingURL=kana-input.js.map
