// Generated by CoffeeScript 2.3.2
(function() {
  'use strict';
  var CND, PD, badge, rpr;

  //###########################################################################################################
  CND = require('cnd');

  rpr = CND.rpr;

  badge = '明快打字机/OPS-MENU';

  // debug                     = CND.get_logger 'debug',     badge
  // alert                     = CND.get_logger 'alert',     badge
  // whisper                   = CND.get_logger 'whisper',   badge
  // warn                      = CND.get_logger 'warn',      badge
  // help                      = CND.get_logger 'help',      badge
  // urge                      = CND.get_logger 'urge',      badge
  // info                      = CND.get_logger 'info',      badge
  PD = require('pipedreams');

  //-----------------------------------------------------------------------------------------------------------
  this.show_or_hide_menu_bar = function() {
    var w;
    w = this.get_window();
    w.setMenuBarVisibility(!w.isMenuBarVisible());
    return null;
  };

  //-----------------------------------------------------------------------------------------------------------
  this.get_transcriptors_submenu = function() {
    var R, i, len, ref, t, tsrnr;
    R = [];
    ref = S.transcriptors;
    for (tsrnr = i = 0, len = ref.length; i < len; tsrnr = ++i) {
      t = ref[tsrnr];
      ((t, tsrnr) => {
        var click, label;
        if (tsrnr < 10) {
          label = `&${tsrnr} ${t.display_name}`;
        } else {
          label = `${tsrnr} ${t.display_name}`;
        }
        click = () => {
          return XE.emit(PD.new_event('^select-transcriptor', {
            tsrnr,
            display_name: t.display_name
          }));
        };
        return R.push({label, click});
      })(t, tsrnr);
    }
    return R;
  };

  //-----------------------------------------------------------------------------------------------------------
  this.add_menu = function() {
    var Menu, menu, template, transcriptors_submenu;
    if (S.transcriptors == null) {
      throw new Error("µ37763 internal error: load transcriptors before adding menu");
    }
    transcriptors_submenu = this.get_transcriptors_submenu();
    template = [];
    this.log(`µ39883 found ${S.transcriptors.length} entries in S.transcriptors`);
    this.log(`µ39883 transcriptors_submenu: ${rpr(transcriptors_submenu)}`);
    //.........................................................................................................
    template.push({
      label: '&File',
      submenu: [
        {
          label: '&imagine',
          click: (function() {
            return alert('a message for you');
          })
        },
        {
          label: '&Quit',
          role: 'close',
          accelerator: 'CmdOrCtrl+Q'
        }
      ]
    });
    //.........................................................................................................
    template.push({
      label: '&Edit',
      submenu: [
        {
          role: 'undo'
        },
        {
          role: 'redo'
        },
        {
          type: 'separator'
        },
        {
          role: 'cut'
        },
        {
          role: 'copy'
        },
        {
          role: 'paste'
        },
        {
          role: 'pasteandmatchstyle'
        },
        {
          role: 'delete'
        },
        {
          role: 'selectall'
        }
      ]
    });
    //.........................................................................................................
    template.push({
      label: '&View',
      submenu: [
        {
          role: 'reload'
        },
        {
          role: 'forcereload'
        },
        {
          role: 'toggledevtools'
        },
        {
          type: 'separator'
        },
        {
          role: 'resetzoom'
        },
        {
          role: 'zoomin'
        },
        {
          role: 'zoomout'
        },
        {
          type: 'separator'
        },
        {
          role: 'togglefullscreen'
        }
      ]
    });
    //.........................................................................................................
    template.push({
      label: '&Transcriptors',
      submenu: transcriptors_submenu
    });
    //.........................................................................................................
    template.push({
      label: '&Help',
      role: 'help',
      submenu: [
        {
          label: 'Learn More',
          click: (() => {
            return this.open_homepage();
          })
        }
      ]
    });
    //.........................................................................................................
    ({Menu} = (require('electron')).remote);
    menu = Menu.buildFromTemplate(template);
    return Menu.setApplicationMenu(menu);
  };

}).call(this);

//# sourceMappingURL=ops-menu.js.map
