// Generated by CoffeeScript 2.3.2
(function() {
  'use strict';
  var CND, PD, alert, badge, debug, help, info, rpr, urge, warn, whisper;

  //###########################################################################################################
  CND = require('cnd');

  rpr = CND.rpr;

  badge = '明快打字机/OPS-CM';

  debug = CND.get_logger('debug', badge);

  alert = CND.get_logger('alert', badge);

  whisper = CND.get_logger('whisper', badge);

  warn = CND.get_logger('warn', badge);

  help = CND.get_logger('help', badge);

  urge = CND.get_logger('urge', badge);

  info = CND.get_logger('info', badge);

  //...........................................................................................................
  PD = require('pipedreams');

  //-----------------------------------------------------------------------------------------------------------
  this._cm_as_pos = function(x) {
    return {
      line: x.line,
      ch: x.ch
    };
  };

  //-----------------------------------------------------------------------------------------------------------
  this./* Unify position-like objects */_cm_order_positions = function(positions) {
    return positions.sort(function(a, b) {
      if (a.line < b.line) {
        return -1;
      }
      if (a.line > b.line) {
        return +1;
      }
      if (a.ch < b.ch) {
        return -1;
      }
      if (a.ch > b.ch) {
        return +1;
      }
      return 0;
    });
  };

  //-----------------------------------------------------------------------------------------------------------
  this._cm_fromto_from_range = function(range) {
    /* Given a `range` with `anchor` and `head` properties (which must both be positions, i.e.
    `{ line, ch, }` objects), return a `{ from, to, }` object where `from` comes always before or coincides
    with `to` in the document. This is needed to convert an object returned e.g. as selection to an
    argument that can be used by `markText()`. */
    var p, q;
    [p, q] = this._cm_order_positions([this._cm_as_pos(range.anchor), this._cm_as_pos(range.head)]);
    return {
      from: p,
      to: q
    };
  };

  //===========================================================================================================

  //-----------------------------------------------------------------------------------------------------------
  this.cm_select_all = function() {
    return CodeMirror.commands.selectAll(S.codemirror.editor);
  };

  this.cm_select_only_first = function() {
    return CodeMirror.commands.singleSelection(S.codemirror.editor);
  };

  this.cm_get_selections = function() {
    return S.codemirror.editor.doc.listSelections();
  };

  this.cm_get_selection_texts = function() {
    return S.codemirror.editor.doc.getSelections();
  };

  this.cm_get_selections_as_fromtos = function() {
    var i, len, ref, results, s;
    ref = this.cm_get_selections();
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      s = ref[i];
      results.push(this._cm_fromto_from_range(s));
    }
    return results;
  };

  // #-----------------------------------------------------------------------------------------------------------
  // @cm_select_only_in_single_line = ->

  //-----------------------------------------------------------------------------------------------------------
  this.cm_set_mark = function(fromto, clasz) {
    var settings;
    this.log('µ52981', `@cm_set_mark ${rpr(fromto)}, ${rpr(clasz)}`);
    settings = {
      className: clasz,
      inclusiveLeft: true,
      inclusiveRight: true
    };
    return S.codemirror.editor.markText(fromto.from, fromto.to, settings);
  };

  //-----------------------------------------------------------------------------------------------------------
  // @cm_clear_translation_mark = ->
  //   return 0 unless S.translation_mark?
  //   S.translation_mark.clear()
  //   S.translation_mark = null
  //   return 1

  //-----------------------------------------------------------------------------------------------------------
  this.cm_get_marks_in_range = function(fromto) {
    return S.codemirror.editor.findMarks(fromto.from, fromto.to);
  };

  this.cm_get_mark_fromtos_in_range = function(fromto) {
    var i, len, ref, results, t;
    ref = this.cm_get_marks_in_position(fromto);
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      t = ref[i];
      results.push(this._cm_as_pos(t.find()));
    }
    return results;
  };

  this.cm_get_marks_in_position = function(position) {
    return S.codemirror.editor.findMarksAt(position);
  };

  this.cm_get_cursor = function() {
    return this._cm_as_pos(S.codemirror.editor.getCursor('head'));
  };

  this.cm_set_cursor = function(position) {
    return S.codemirror.editor.setCursor(position);
  };

  this./* TAINT might want to use options */cm_get_text = function(fromto) {
    return S.codemirror.editor.getRange(fromto.from, fromto.to);
  };

  this.cm_text_from_mark = function(mark) {
    return this.cm_get_text(mark.find());
  };

  this.cm_text_from_line_idx = function(line_idx) {
    return S.codemirror.editor.getLine(line_idx);
  };

  this.cm_replace_selection = function(text) {
    return S.codemirror.editor.doc.replaceSelection(text);
  };

  this.cm_range_is_point = function(fromto) {
    return CND.equals(fromto.from, fromto.to);
  };

  //-----------------------------------------------------------------------------------------------------------
  this.cm_select = function(fromto) {
    this.log('µ53082', `cm_select: ${rpr(fromto)}`);
    return S.codemirror.editor.setSelection(fromto.from, fromto.to);
  };

  //-----------------------------------------------------------------------------------------------------------
  this.position_and_clasz_from_mark = function(mark) {
    var fromto, ref;
    fromto = mark.find();
    return {
      from: this._cm_as_pos(fromto.from),
      to: this._cm_as_pos(fromto.to),
      clasz: (ref = mark.className) != null ? ref : ''
    };
  };

}).call(this);

//# sourceMappingURL=ops-cm.js.map
