// Generated by CoffeeScript 2.4.1
(function() {
  'use strict';
  var CND, PD, add_context_menu, badge, rpr;

  //###########################################################################################################
  CND = require('cnd');

  rpr = CND.rpr;

  badge = '明快打字机/OPS-MENU';

  // debug                     = CND.get_logger 'debug',     badge
  // alert                     = CND.get_logger 'alert',     badge
  // whisper                   = CND.get_logger 'whisper',   badge
  // warn                      = CND.get_logger 'warn',      badge
  // help                      = CND.get_logger 'help',      badge
  // urge                      = CND.get_logger 'urge',      badge
  // info                      = CND.get_logger 'info',      badge
  PD = require('pipedreams');

  add_context_menu = require('electron-context-menu');

  //-----------------------------------------------------------------------------------------------------------
  this.show_or_hide_menu_bar = function() {
    var w;
    w = this.get_window();
    w.setMenuBarVisibility(!w.isMenuBarVisible());
    return null;
  };

  //-----------------------------------------------------------------------------------------------------------
  this.get_transcriptors_submenu = function() {
    var R, i, j, len, len1, ref, ref1, t, tsnr;
    R = [];
    ref = S.transcriptors;
    for (tsnr = i = 0, len = ref.length; i < len; tsnr = ++i) {
      t = ref[tsnr];
      ((t, tsnr) => {
        var click, label;
        if (tsnr < 10) {
          label = `toggle &${tsnr} [${t.sigil}] ${t.display_name}`;
        } else {
          label = `toggle ${tsnr} [${t.sigil}] ${t.display_name}`;
        }
        click = () => {
          return this.insert_tsm(tsnr, {
            toggle: true
          });
        };
        return R.push({label, click});
      })(t, tsnr);
    }
    ref1 = S.transcriptors;
    for (tsnr = j = 0, len1 = ref1.length; j < len1; tsnr = ++j) {
      t = ref1[tsnr];
      ((t, tsnr) => {
        var click, label;
        if (tsnr < 10) {
          label = `add &${tsnr} [${t.sigil}] ${t.display_name}`;
        } else {
          label = `add ${tsnr} [${t.sigil}] ${t.display_name}`;
        }
        click = () => {
          return this.insert_tsm(tsnr, {
            toggle: false
          });
        };
        return R.push({label, click});
      })(t, tsnr);
    }
    return R;
  };

  //-----------------------------------------------------------------------------------------------------------
  this.add_menu = function() {
    var Menu, menu, template, transcriptors_submenu;
    if (S.transcriptors == null) {
      throw new Error("µ37763 internal error: load transcriptors before adding menu");
    }
    transcriptors_submenu = this.get_transcriptors_submenu();
    template = [];
    this.log(`µ39883 found ${S.transcriptors.length} entries in S.transcriptors`);
    this.log(`µ39883 transcriptors_submenu: ${rpr(transcriptors_submenu)}`);
    //.........................................................................................................
    template.push({
      label: '&File',
      submenu: [
        {
          label: '&imagine',
          click: (function() {
            return alert('a message for you');
          })
        },
        {
          label: '&Quit',
          role: 'close',
          accelerator: 'CmdOrCtrl+Q'
        }
      ]
    });
    //.........................................................................................................
    template.push({
      label: '&Edit',
      submenu: [
        {
          role: 'undo'
        },
        {
          role: 'redo'
        },
        {
          type: 'separator'
        },
        {
          role: 'cut'
        },
        {
          role: 'copy'
        },
        {
          role: 'paste'
        },
        {
          role: 'pasteandmatchstyle'
        },
        {
          role: 'delete'
        },
        {
          role: 'selectall'
        }
      ]
    });
    //.........................................................................................................
    template.push({
      label: '&View',
      submenu: [
        {
          role: 'reload'
        },
        {
          role: 'forcereload'
        },
        {
          role: 'toggledevtools'
        },
        {
          type: 'separator'
        },
        {
          role: 'resetZoom'
        },
        {
          role: 'zoomIn',
          accelerator: 'Ctrl+='
        },
        {
          role: 'zoomOut'
        },
        {
          // { role: 'zoomIn', accelerator: 'Ctrl+=',              }
          // { role: 'zoomOut', accelerator: 'CmdOrCtrl+-', }
          type: 'separator'
        },
        {
          role: 'togglefullscreen'
        }
      ]
    });
    //.........................................................................................................
    template.push({
      label: '&Transcriptors',
      submenu: transcriptors_submenu
    });
    //.........................................................................................................
    template.push({
      label: '&Help',
      role: 'help',
      submenu: [
        {
          label: 'Learn More',
          click: (() => {
            return this.open_homepage();
          })
        }
      ]
    });
    //.........................................................................................................
    ({Menu} = (require('electron')).remote);
    menu = Menu.buildFromTemplate(template);
    Menu.setApplicationMenu(menu);
    return null;
  };

  //-----------------------------------------------------------------------------------------------------------
  this.add_context_menu = function() {
    /* TAINT see https://github.com/sindresorhus/electron-context-menu for format */
    add_context_menu({
      prepend: (defaultActions, params, browserWindow) => {
        return [
          {
            label: 'Rainbow',
            // Only show it when right-clicking images
            visible: params.mediaType === 'image'
          }
        ];
      }
    });
    return null;
  };

}).call(this);

//# sourceMappingURL=ops-menu.js.map
