// Generated by CoffeeScript 2.3.2
(function() {
  'use strict';
  var CND, _lognr, alert, badge, debug, help, info, jr, rpr, skip_events, urge, warn, whisper;

  //###########################################################################################################
  CND = require('cnd');

  rpr = CND.rpr;

  badge = '明快打字机/OPS-LOGGER';

  debug = CND.get_logger('debug', badge);

  alert = CND.get_logger('alert', badge);

  whisper = CND.get_logger('whisper', badge);

  warn = CND.get_logger('warn', badge);

  help = CND.get_logger('help', badge);

  urge = CND.get_logger('urge', badge);

  info = CND.get_logger('info', badge);

  //...........................................................................................................
  ({jr} = CND);

  // { inspect, }              = require 'util'
  // xrpr                      = ( x ) -> inspect x, { colors: yes, breakLength: Infinity, maxArrayLength: Infinity, depth: Infinity, }
  _lognr = 0;

  // '^input'
  skip_events = new Set(['^ignore-delete', '^keyboard']);

  //-----------------------------------------------------------------------------------------------------------
  this.log_almost_all_events = function(key, d) {
    var logger, lognr, message, ref, v;
    // whisper 'µ99823', key #, jr d
    if (skip_events.has(key)) {
      return;
    }
    _lognr += +1;
    lognr = `${_lognr}`.padStart(5, '_');
    v = (ref = d.value) != null ? ref : {};
    logger = jQuery('#logger');
    while (logger.children().length > 1000) {
      (logger.find(':first-child')).remove();
    }
    message = rpr(v);
    // message = ( k for k         of d.value                ).join ', '
    // message = switch key
    //   when '^kblevel' then  ( k for k, toggle of S.kblevels when toggle ).join ', '
    //   else                  ( k for k         of d.value                ).join ', '
    //.........................................................................................................
    logger.append(`<div>${lognr}: ${rpr(key)}: ${message}</div>`);
    console.log(lognr, key, d);
    logger.scrollTop(logger[0].scrollHeight);
    //.........................................................................................................
    return null;
  };

  //-----------------------------------------------------------------------------------------------------------
  this.log = function(...P) {
    var logger, lognr, p, text;
    /* TAINT code duplication */
    _lognr += +1;
    lognr = `${_lognr}`.padStart(5, '_');
    text = ((function() {
      var i, len, results;
      results = [];
      for (i = 0, len = P.length; i < len; i++) {
        p = P[i];
        results.push(CND.isa_text(p) ? p : rpr(p));
      }
      return results;
    })()).join(' ');
    logger = jQuery('#logger');
    while (logger.children().length > 1000) {
      (logger.find(':first-child')).remove();
    }
    /* TAINT should escape text (or accept HTML?) */
    console.log(lognr, text);
    info(lognr, text);
    logger.append(`<div>${lognr}: ${text}</div>`);
    logger.scrollTop(logger[0].scrollHeight);
    return null;
  };

}).call(this);

//# sourceMappingURL=ops-logger.js.map
