// Generated by CoffeeScript 2.4.1
(function() {
  /* This module is used to communicate values betwenn main process and renderer process */
  module.exports = {};

}).call(this);

//# sourceMappingURL=snarf.js.map
