// Generated by CoffeeScript 2.3.2
(function() {
  // cannot 'use strict'

  //###########################################################################################################
  var CND, TEACUP, alert, badge, debug, help, info, log, njs_fs, njs_path, rpr, urge, warn, whisper;

  njs_path = require('path');

  njs_fs = require('fs');

  //...........................................................................................................
  CND = require('cnd');

  rpr = CND.rpr.bind(CND);

  badge = '明快打字机/TEMPLATES';

  log = CND.get_logger('plain', badge);

  info = CND.get_logger('info', badge);

  whisper = CND.get_logger('whisper', badge);

  alert = CND.get_logger('alert', badge);

  debug = CND.get_logger('debug', badge);

  warn = CND.get_logger('warn', badge);

  help = CND.get_logger('help', badge);

  urge = CND.get_logger('urge', badge);

  //...........................................................................................................
  // MKTS                      = require './main'
  TEACUP = require('coffeenode-teacup');

  // CHR                       = require 'coffeenode-chr'
  //...........................................................................................................
  // _STYLUS                   = require 'stylus'
  // as_css                    = STYLUS.render.bind STYLUS
  // style_route               = njs_path.join __dirname, '../src/mingkwai-typesetter.styl'
  // css                       = as_css njs_fs.readFileSync style_route, encoding: 'utf-8'
  //...........................................................................................................

  //===========================================================================================================
  // TEACUP NAMESPACE ACQUISITION
  //-----------------------------------------------------------------------------------------------------------
  Object.assign(this, TEACUP);

  //-----------------------------------------------------------------------------------------------------------
  this.FULLHEIGHTFULLWIDTH = this.new_tag(function(...P) {
    return this.TAG('fullheightfullwidth', ...P);
  });

  this.OUTERGRID = this.new_tag(function(...P) {
    return this.TAG('outergrid', ...P);
  });

  this.TOPBAR = this.new_tag(function(...P) {
    return this.TAG('topbar', ...P);
  });

  this.CONTENT = this.new_tag(function(...P) {
    return this.TAG('content', ...P);
  });

  this.MIDBAR = this.new_tag(function(...P) {
    return this.TAG('midbar', ...P);
  });

  this.SHADE = this.new_tag(function(...P) {
    return this.TAG('shade', ...P);
  });

  this.SCROLLER = this.new_tag(function(...P) {
    return this.TAG('scroller', ...P);
  });

  this.BOTTOMBAR = this.new_tag(function(...P) {
    return this.TAG('bottombar', ...P);
  });

  this.LBBAR = this.new_tag(function(...P) {
    return this.TAG('lbbar', ...P);
  });

  this.RBBAR = this.new_tag(function(...P) {
    return this.TAG('rbbar', ...P);
  });

  //...........................................................................................................
  this.JS = this.new_tag(function(route) {
    return this.SCRIPT({
      type: 'text/javascript',
      src: route
    });
  });

  this.CSS = this.new_tag(function(route) {
    return this.LINK({
      rel: 'stylesheet',
      href: route
    });
  });

  // @STYLUS               = ( source ) -> @STYLE {}, _STYLUS.render source

  //===========================================================================================================

  //-----------------------------------------------------------------------------------------------------------
  this.get_row_html = function(key_value_pairs) {
    return this.render(() => {
      return this.TR('.candidate', () => {
        var i, key, len, results, value;
        results = [];
        for (i = 0, len = key_value_pairs.length; i < len; i++) {
          [key, value] = key_value_pairs[i];
          results.push(this.TD(`.${key}`, value.toString()));
        }
        return results;
      });
    });
  };

  //-----------------------------------------------------------------------------------------------------------
  this.main_2 = function() {
    //.........................................................................................................
    return this.render(() => {
      this.DOCTYPE(5);
      this.META({
        charset: 'utf-8'
      });
      // @META 'http-equiv': "Content-Security-Policy", content: "default-src 'self'"
      // @META 'http-equiv': "Content-Security-Policy", content: "script-src 'unsafe-inline'"
      this.TITLE('明快打字机');
      // @LINK rel: 'shortcut icon', href: './favicon.icon'
      /* ------------------------------------------------------------------------------------------------ */
      /* The Tomkel-Harders device to make sure jQuery and other libraries are correctly                  */
      /* loaded and made available even in Electron; see                                                  */
      /*   https://github.com/electron/electron/issues/254#issuecomment-183483641                         */
      /*   https://stackoverflow.com/a/37480521/7568091                                                   */
      /* -------------------------- THIS LINE MUST COME BEFORE ANY IMPORTS ------------------------------ */
      this.SCRIPT("if (typeof module === 'object') {window.module = module; module = undefined;}");
      /* ------------------------------------------------------------------------------------------------ */
      this.JS('./jquery-3.3.1.js');
      this.CSS('./reset.css');
      this.CSS('./styles-01.css');
      /* ------------------------------------------------------------------------------------------------ */
      /* CodeMirror                                                                                       */
      this.CSS('./codemirror/lib/codemirror.css');
      this.CSS('./codemirror/addon/fold/foldgutter.css');
      this.CSS('./codemirror/addon/dialog/dialog.css');
      this.CSS('./codemirror/theme/monokai.css');
      this.JS('./codemirror/lib/codemirror.js');
      this.JS('./codemirror/mode/javascript/javascript.js');
      this.JS('./codemirror/mode/coffeescript/coffeescript.js');
      this.JS('./codemirror/addon/search/searchcursor.js');
      this.JS('./codemirror/addon/search/search.js');
      this.JS('./codemirror/addon/dialog/dialog.js');
      this.JS('./codemirror/addon/edit/matchbrackets.js');
      this.JS('./codemirror/addon/edit/closebrackets.js');
      this.JS('./codemirror/addon/comment/comment.js');
      this.JS('./codemirror/addon/wrap/hardwrap.js');
      this.JS('./codemirror/addon/fold/foldcode.js');
      this.JS('./codemirror/addon/fold/brace-fold.js');
      this.JS('./codemirror/keymap/sublime.js');
      /* -------------------------- THIS LINE MUST COME AFTER ANY IMPORTS ------------------------------- */
      this.CSS('./styles-99.css');
      this.SCRIPT("if (window.module) module = window.module;");
      /* ------------------------------------------------------------------------------------------------ */
      //=======================================================================================================
      this.FULLHEIGHTFULLWIDTH(() => {
        return this.OUTERGRID(() => {
          this.TOPBAR(() => {
            /* TAINT multiple wrapping needed? */
            return this.CONTENT(() => {
              return this.TEXTAREA('#codemirror');
            });
          });
          this.MIDBAR(() => {
            this.SHADE('.background');
            this.SCROLLER(() => {
              return this.TABLE('#candidates', () => {
                return this.TBODY(() => {
                  return this.TR(() => {
                    this.TD('.value', "MingKwai");
                    this.TD('.glyph', "明快打字机");
                    return this.TD('.value', "TypeWriter");
                  });
                });
              });
            });
            return this.SHADE('.foreground');
          });
          this.LBBAR(() => {
            return 'L';
          });
          this.BOTTOMBAR(() => {
            return this.DIV('#text-input.inbox', {
              contenteditable: 'true'
            });
          });
          return this.RBBAR(() => {
            return 'R';
          });
        });
      });
      //=======================================================================================================
      this.JS('./ops.js');
      return null;
    });
  };

  //-----------------------------------------------------------------------------------------------------------
  this.minimal = function() {
    //.........................................................................................................
    return this.render(() => {
      this.DOCTYPE(5);
      this.META({
        charset: 'utf-8'
      });
      // @META 'http-equiv': "Content-Security-Policy", content: "default-src 'self'"
      // @META 'http-equiv': "Content-Security-Policy", content: "script-src 'unsafe-inline'"
      this.JS('./jquery-3.3.1.js');
      this.CSS('./reset.css');
      this.CSS('./styles-01.css');
      this.CSS('./styles-99.css');
      this.TITLE('明快打字机');
      this.DIV(() => {
        return "helo world";
      });
      this.JS('./ops.js');
      return null;
    });
  };

  // #-----------------------------------------------------------------------------------------------------------
// @layout = @FLOAT_layout

}).call(this);

//# sourceMappingURL=templates.js.map
