// Generated by CoffeeScript 2.3.2
(function() {
  'use strict';
  var CND, Intertype, alert, all_keys_of, badge, debug, declare, has_keys, help, info, intertype, isa, jr, rpr, size_of, type_of, types_of, urge, validate, warn, whisper;

  //###########################################################################################################
  CND = require('cnd');

  rpr = CND.rpr;

  badge = '明快打字机/TYPES';

  debug = CND.get_logger('debug', badge);

  alert = CND.get_logger('alert', badge);

  whisper = CND.get_logger('whisper', badge);

  warn = CND.get_logger('warn', badge);

  help = CND.get_logger('help', badge);

  urge = CND.get_logger('urge', badge);

  info = CND.get_logger('info', badge);

  jr = JSON.stringify;

  Intertype = (require('intertype')).Intertype;

  intertype = new Intertype;

  ({isa, validate, type_of, types_of, size_of, declare, has_keys, all_keys_of} = intertype.export_methods());

  //-----------------------------------------------------------------------------------------------------------
  declare('position', {
    tests: {
      '? isa pod': function(x) {
        return this.isa.object(x);
      },
      '? has_keys line, ch': function(x) {
        return this.has_keys(x, 'line', 'ch');
      },
      '?.line is a count': function(x) {
        return this.isa.count(x.line);
      },
      '?.ch is a count': function(x) {
        return this.isa.count(x.ch);
      }
    }
  });

  //-----------------------------------------------------------------------------------------------------------
  declare('range', {
    tests: {
      '? isa pod': function(x) {
        return this.isa.object(x);
      },
      '? has_keys from, to': function(x) {
        return this.has_keys(x, 'from', 'to');
      },
      '?.from is a position': function(x) {
        return this.isa.position(x.from);
      },
      '?.to is a position': function(x) {
        return this.isa.position(x.to);
      }
    }
  });

  //###########################################################################################################
  if (module.parent == null) {
    null;
  }

}).call(this);

//# sourceMappingURL=types.js.map
